# Generated by Django 2.2.3 on 2019-07-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestcom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
