# Generated by Django 2.2.3 on 2019-07-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestcom', '0003_clients_commandes_lunette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='photo',
        ),
    ]
