# Generated by Django 2.2.3 on 2019-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestcom', '0004_remove_clients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='date_add',
            field=models.DateField(),
        ),
    ]
